### ISSUE TITLE
the mod isn't working for every new character

### ISSUE THREAD

**Issue by Hamburger666** [kgoyo/BossCursor#1]
i am using HERO's mod, calamity and calamity music mod, fargo's mutant mod, veinminer, omniswing, recipe browser, alchemist NPC lite max stat plus extra, shorter respawn time, yet another boss health bar and magic storage.
most of the times it works but when i create a new character then it doesn't work properly anymore and i have to re-install the mod, sometimes the boss curser just dissappers during the boss fight and then never appearing again

**Comment by kgoyo** [comment]
are there any errors in the log? Are you disabling the cursor, there is a hotkey for that. Please provide more info

**Comment by Hamburger666** [comment]
there's a log?
also the cursor doesn't go back up even when i press the toggle button

**Comment by Hamburger666** [comment]
wait i somehow fixed it nvm then

**Comment by kgoyo** [comment]
please leave the solution to your problem, so that other people can use it in case they run into something similar.

**Comment by Hamburger666** [comment]
well it broke again, last time i fixed it by reloading all mods for something like 30 times, this time i reloaded for 50 times and it still doesn't function

**Comment by kgoyo** [comment]
I'd advice you check out the tmodloader discord for support, you are simply not providing enough information here for me.
